name: Lint

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ── Terraform formatting check ──────────────────────────
      - name: Terraform fmt
        run: terraform -chdir=terraform fmt -check

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master   # <- working ref
        with:
          scandir: files
